fix(jni): align build file generation
Currently, we generate the Build.cs file on the Module scope, and not on
interface scope, like in other communication protocols (olink, monitor,
msgbus).

Because of this, ue4 gets the following error while building:

  ERROR: Unable to determine UHT module type for ...

... for modules without interfaces, for example the CustomTypes module
of goldenmaster.

Fix this, by moving the generation of Build.cs file to the interface
scope.